name: BossBarMessage
version: '${project.version}'
main: io.github.endergamerhun.bossbarmessage.BossBarMessage
api-version: 1.18

permissions:
  bossbarmessage.broadcast:
    description: Broadcast on the BossBar
# PLANS:
#  bossbarmessage.message:
#    description: Show bossbar to a specific player
#  bossbarmessage.admin:
#    description: Admin commands

commands:
  bbbroadcast:
    permission: bossbarmessage.broadcast
# PLANS:
#  bbsend:
#    permission: bossbarmessage.message
#  bossbarmessage:
#    permission: bossbarmessage.admin
